
[general]
live_config_reload = true
import = [
		"~/dotfiles/.config/alacritty/marine_dark.toml"
]

[window]
decorations = "None"
dimensions = { columns = 144, lines = 36}
opacity = 0.85

[font]
normal = {family = "FantasqueSansM Nerd Font", style="Regular"}
size = 16

[cursor]
style = {shape = "Block", blinking = "Always"}
blink_interval = 500

