
[general]
live_config_reload = true
import = [
		"~/dotfiles/.config/alacritty/everblush.toml"
]

[window]
decorations = "None"
dimensions = { columns = 150, lines = 40}
opacity = 0.85
padding = {x = 5, y = 3}

[font]
normal = {family = "FantasqueSansM Nerd Font", style="Regular"}
size = 16

[cursor]
style = {shape = "Block", blinking = "Always"}
blink_interval = 500

