
[general]
live_config_reload = true
import = [
		"~/dotfiles/.config/alacritty/rose_pine.toml"
]

[window]
decorations = "None"
startup_mode = "Maximized"

[font]
normal = {family = "FantasqueSansM Nerd Font", style="Regular"}
size = 21



[cursor]
style = {shape = "Block", blinking = "Always"}
blink_interval = 500

